<div class="checkout-success">
    <p>
        <?php
            $objHostedFailure = $this->getHostedFailureMessage();
            if (isset($objHostedFailure['orderid'])) {
                echo $block->escapeHtml(__('Your Order #') . $objHostedFailure['orderid']);
            }else if (isset($objHostedFailure['hostedfailure']['status'])) {
                echo $block->escapeHtml(__(' is ') . strtolower($objHostedFailure['hostedfailure']['status']));
            }else if (isset($objHostedFailure['hostedfailure']['reason_message'])) {
                echo $block->escapeHtml(__(' because of ') . $objHostedFailure['hostedfailure']['reason_message']);
            }else{
                echo $block->escapeHtml(__(' Order Failed '));
            }
            
        ?>
    </p>
</div>


